### ISSUE TITLE
删除微博 API 无效

### ISSUE THREAD

**Issue by ghost** [andelf/pyqqweibo#5]
删除微博 API 无效，key 和 secret 肯定有效的。

测试环境 py2.7 32bit.

代码如下

`````` python
import model
import commons

from qqweibo.auth import OAuthHandler
from qqweibo.api import API
import qq_conf

oauth = OAuthHandler(qq_conf.qq_appkey, qq_conf.qq_appscrt)

key = "77c4bdf5ea234609980c5988fdxxxxxx"
secret = "29f439fb8d84049d0c24ba9b89oooooo"
oauth.set_access_token(key, secret)

api = API(oapi)
me = api.me()

print 'statuses_count:', me.statuses_count

tweets = oapi.timeline.home()
for i in tweets:
    print i.text
    i.delete()

print 'statuses_count:', me.statuses_count```


``````

**Comment by andelf** [comment]
ɾĲԼİ, ȷǲԼ...

2011/11/8 Shuge Lee <
reply@reply.github.com>

**Comment by ghost** [comment]
Could you speak English or Chinese ?

**Comment by ifduyue** [comment]
-_-!!!

**Comment by andelf** [comment]
@shuge
:) post directly from gmail, and github haven't supported it.
你删除的不是自己的吧, 你先确认下是不是自己的...
make sure you are deleting your own post~....

**Comment by andelf** [comment]
@shuge
home timeline 返回的不一定是自己的。
所以请访问 t.self 属性， 确认为 True 后则可删除。

make sure your Tweet is created by yourself, then you can delete it.

**Comment by andelf** [comment]
有问题再开个issue 吧， 我觉得这个是误报。

**Comment by andelf** [comment]
@lyxint 囧了。 从gmail直接回复不支持中文。

**Comment by ghost** [comment]
你用哪个厂商的浏览器，哪个版本？

我回头测试一下。
SINA 的 home_timeline 是自己，不确定 qq 的是怎么回事。

**Comment by ghost** [comment]
我确定那些是我发的，我确定 删除API 不可用，我还确定这个不是缓存问题（不是腾讯服务器缓存）。

**Comment by andelf** [comment]
@shuge ok, 今天下班前给你解决.

**Comment by ghost** [comment]
您应该 reopen 一下

您不是给我解决啊，您是给所有使用您这个 SDK 的人解决 :)　

平时上班是不是被 boss 折腾出职业病职业反应了？

**Comment by andelf** [comment]
@shuge  ....自己reopen

**Comment by andelf** [comment]
@shuge 之前你open issue的时候我测试没问题。。
现在帮你解决的时候我这里还是没问题。。。。
囧。
另外， timeline.home() 是返回所有人的tweet 。。。 另外。。。 真的可以删除。。不用怀疑。

**Comment by andelf** [comment]
不用开issue 了。。。
我这里真的没问题。。。

@shuge

**Comment by andelf** [comment]
其他人应该也没遇到这个问题。
@shuge

**Comment by ghost** [comment]
我没有权限 reopen (似乎 GitHub 里面如果是作者 close ，非开发者/其它人是没有权限 reopen的）。

请贴出你的测试代码，越短越好。

**Comment by andelf** [comment]
@shuge 
。。。。。我的代码和你的一样。
同时我确认了那条微博是不是我的。
以及， 你确认下你的API权限等级够不够。

我觉得没必要reopen。 没有办法重现
另外参考 tests.py

**Comment by andelf** [comment]
@shuge for 循环可能有问题。因为原因已经给你说了。。
我总觉得你没有仔细看我给你说的。。

home() 返回所有tweet， 所以你不能删除别人的
