### ISSUE TITLE
运行auth例子失败

### ISSUE THREAD

**Issue by linkerlin** [andelf/pyqqweibo#7]
[root@test84 examples]# python example-auth.py 
Traceback (most recent call last):
  File "example-auth.py", line 15, in <module>
    from qqweibo import OAuthHandler, API, JSONParser
ImportError: cannot import name OAuthHandler

**Comment by andelf** [comment]
那啥，最近更新oauth2.0的，忘记修改exmaple.py了。。随后改上
现在auth里有三个auth handler了

**Comment by andelf** [comment]
fixed!
