### ISSUE TITLE
OAuth2_0_Handler get_access_token issue, cause example-auth.py fail

### ISSUE THREAD

**Issue by raully7** [andelf/pyqqweibo#8]
The example-auth code can't get the correct response, server will return 38 with a error message "check sign error".

I believe that's because it doesn't pass the correct access_token as the bug in function get_access_token(L212 - L221):

``` python
        refresh_token = response_args.get('refresh_token', None)
        access_token = response_args.get('access_token', None)
        openid = response_args.get('openid', None)

        if refresh_token is not None:
            response_args = self.refresh(refresh_token)

        self.refresh_token = refresh_token
        self.access_token = access_token
        self.openid = openid
```

Self.refresh will get a new access_token and refresh_token, but we always keep the old ones.

**Comment by andelf** [comment]
sorry I just forgot to push my local repo to github. :)
